name: Build

on:  
#   release:
#     types: [published]
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Build
  #     run: cargo build --bin wol
  #   - name: Run tests
  #     run: cargo test

  build-linux:
    runs-on: unbuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run:
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          cargo build
    - name: Run tests
      run: cargo test
